### ISSUE TITLE
Policy lab offsite 2 in Feb 2020

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/policy-lab#14]
Getting tactical about the policy lab...

Plan projects
Set expectations and clarify roles
Set project management/meeting cadence

**Comment by sammodabber** [comment]
Scheduled for Wednesday, 2/12 at 1pm

NEED: 
 - Agenda
 - Purpose
 - Goal
 - Meeting structure

**Comment by danielhonker** [comment]
Closeout tasks:

- [x] Share photos and notes
- [x] Schedule a meeting to start scoping a policy ecosystem map

**Comment by sammodabber** [comment]
Meeting Notes: https://docs.google.com/document/d/1-qppfPFkNEJMn37ZpMxhnIokbxAC_u5jAZYkbc7ttBo/edit?usp=sharing
