### ISSUE TITLE
Scope the policy inventory and ecosystem map

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/policy-lab#2]
To understand the current ecosystem of policy areas touching digital services, and who controls or influences these areas

## To do
- [x] Brain dump: list digital policy areas, create the architecture/data fields, fill in what information we know @danielhonker 
- [ ] Put out a call to the team to add digital policy areas, do some desk research @sammodabber 
- [ ] Recruit someone to config a network map -- maybe @manlinyao 

## Artifacts
[Scope and approach](https://docs.google.com/document/d/1Vdt6--jfZrczT1x8-GACxGl2IBHLkOeJtJyAhsYwf2c/edit#)

[Matrix of policy areas](https://airtable.com/tbl3tkzq0c6TcN6AA/viwBTqdNXjJonJpcs?blocks=hide)

**Comment by danielhonker** [comment]
Start drafting in a doc before we meet on March 5.

**Comment by danielhonker** [comment]
[Draft scope](https://docs.google.com/document/d/1Vdt6--jfZrczT1x8-GACxGl2IBHLkOeJtJyAhsYwf2c/edit#)

**Comment by sammodabber** [comment]
Create form for policy areas to fill into airtable @danielhonker

**Comment by danielhonker** [comment]
@sammodabber Here's a first cut at a facilitation plan for doing this virtually. Let's talk more. https://docs.google.com/document/d/1u6xzl7sIb-zp3-EQ3EfzhYEympB-eqEGdIfVZsvPytw/edit#

**Comment by danielhonker** [comment]
@sammodabber To your point about wanting to clean up our GH issues -- since this issue is about scoping/planning the ecosystem map, should we call it closed, and use #6 as the next step to actually create the thing?
