### ISSUE TITLE
Content strategist onboarding/transition plan

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/policy-lab#28]
There are some big unknowns/risks that make the transition very ambiguous right now (e.g., hiring freeze). I started putting together a transition outline understanding that the transition will be delayed. The bottom of the doc has a risk table to try to distill questions and action items out of the ambiguity. Wanted to share for awareness -- and please identify anything missing.

https://docs.google.com/document/d/1GeNcpxy7jIIHRjbVjy_KW3zjRzLVIoibfT5wWlvRhn0/edit?usp=sharing

**Comment by srigdon** [comment]
Update: 
- @srigdon to give PL and content team a schedule by sprints and percentage of time for each team by EOD 8/11 (end of PL sprint 4).
