### ISSUE TITLE
Review Medium article and publish

### ISSUE THREAD

**Issue by sammodabber** [cityofaustin/policy-lab#35]
https://docs.google.com/document/d/1tivG0qYRx82EeAafHR6K6C5mPCVPJ0wLZcOQ4aNsLK4/edit?usp=sharing

**Comment by sammodabber** [comment]
Assigned to Sarah Rigdon

**Comment by danielhonker** [comment]
[Published!](https://medium.com/civiqueso/data-privacy-digital-board-game-edition-c674cfa53c81)
