### ISSUE TITLE
Catalog policy barriers for digital services

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/policy-lab#48]
We want to understand what policy gaps or barriers stand in the way of launching Austin.gov and its features on the digital services roadmap. We will use this information to prioritize policy issues to focus on in support of more human-centered and modern digital services. 

## Checklist
- [x] Plan out the approach
- [x] Plan and implement either of those
- [x] Set up miro board (or however we will facilitate this)
- [x] Export to be able to do sensemaking

## Desired outcomes
- Understanding of what policy gaps/barriers are blocking the launch of Austin.gov (as-is and near future)
- Understanding of what policy gaps/barriers might pop up further down the roadmap for digital services (longer term)
- Priorities for policy projects supporting digital services -- and able to power-map approaches 

## Approach
1. Review the digital services roadmap ([slides](https://docs.google.com/presentation/d/1UaHCDrKSrSGIP1bdq1awNxfB_bdKwsNcVPZhRmKOO2c/edit#slide=id.g830e4912b7_0_1123), [Zenhub](https://github.com/cityofaustin/techstack#workspaces/techstack-5a78b88e1ce69f3510b678ef/roadmap?repos=185443602), ~[miro](https://miro.com/app/board/o9J_kt480Yc=/), roadmunk versions~) to identify what policy issues might be relevant to current or future plans. 

2. Meet with (or survey) the Austin.gov team leads: content, design, dev, product. 
- Ask them via emoji vote whether to do a meeting or survey. 

Ask them: 
  - Where have you been blocked from shipping the website due to: rules, perceptions of rules, lack of agreement, or lack of direction? 
  - What blockers can you see down the road that might stop or slow new features or functionality?
  - For each issue that is policy-related: How big of a deal is this to your work? Who influences or controls this issue? Do the players involved agree on this? Is there existing policy or anything documented?

3. Categorize the policy issues identified:
  - Urgent issue or something for the future
  - Size of impact on digital services roadmap
  - Size of effort to resolve it

4. Create and share an ongoing way to identify policy issues 
We've created and used two of these to date. Should reconcile: [Airtable form](https://airtable.com/shrUiY6fKxwa4OFzB), [Github issue](https://github.com/cityofaustin/policy-lab/issues/templates/edit)

## Questions to resolve
How do we know something is a "policy issue"?
- Might be hard to identify a policy issue without doing service design first. 
- Policies vs. procedures distinction. 

How might we define urgency, impact, effort?

What does "good" and "bad" policy look like?
- Ex: accessible, flexible, iterative, whether it is followed, whether it is effective, can people implement it, is it feasible, resourcing, enforcement
  - What goes into making good policy?
  - How does it fit into goals, outcomes, practices, and processes?

## Work products
Potential deliverables:
- Catalog of policy issues tagged with short/long term impact, degree of impact, complexity, influencers/stakeholders
  - [Running list of policy issues identified to date](https://airtable.com/tbl3tkzq0c6TcN6AA/viwBTqdNXjJonJpcs?blocks=hide)

**Comment by danielhonker** [comment]
Info sources: 

[Roadmap slides](https://docs.google.com/presentation/d/1UaHCDrKSrSGIP1bdq1awNxfB_bdKwsNcVPZhRmKOO2c/edit#slide=id.g74c655319f_39_63)
- Looks mostly up to date at a high level
- We're fasttracking all the content

Content and policy debt tracking
- Beefing up the content debt template to identify needs for research, service design, policy, tech building blocks needed
- Tracking this in github issue templates

[Miro](https://miro.com/app/board/o9J_kqjDfCI=/)
- SEO: who on your team is managing your SEO strategy so that it makes sense, and you are not conflicting with another program's/department's SEO

[Zenhub](https://github.com/cityofaustin/techstack#workspaces/techstack-5a78b88e1ce69f3510b678ef/roadmap?repos=185443602)

~Roadmunk~

**Comment by srigdon** [comment]
To do:  

- [ ] Draft a message to web team leads to explain our goal and ask for 1 hr to do an ideation session, or if time is short, send a survey. 
- [ ] Plan and implement either of those
- [ ] Send documentation and feedback loop 
- [ ] Let's define, document: 
    - What is good policy?
    - What goes into making good policy?
    - How does it fit into goals, outcomes, practices, and processes?

**Comment by danielhonker** [comment]
I just sent a message to the team leads on slack with emoji voting on meeting vs. survey. Will let you know the results...

**Comment by danielhonker** [comment]
Votes are in -- we'll do a meeting. @sammodabber @srigdon what's good timing in the next two weeks for a 1-hour session with the web team leads? We have a recurring program leads meeting, but those usually have full agendas, so I don't want to cannibalize that time.

**Comment by sammodabber** [comment]
Next Wed, 8/12 looks open in the afternoon for most people

**Comment by danielhonker** [comment]
I want to schedule the meeting for as convenient a time as possible for folks -- not disrupt flows. So if Wed pm works, that's great.

**Comment by danielhonker** [comment]
@sammodabber @sarahscottr I put together a [miro board for this session](https://miro.com/welcomeonboard/zyPkgIhbHNzmhOLSsVM20qEijaVj2xu42RrxKbv6bPxs0ySax3x6p2N5yfoHhj1f). Lmn your thoughts.

**Comment by danielhonker** [comment]
Exported the miro board into an [airtable base](https://airtable.com/tbllO2E6c1cdxJq8p/viwr80pcwhw2nRT89?blocks=hide). Added fields to start to synthesize.
